### ISSUE TITLE
Known Issue - facebook updated protocols

### ISSUE THREAD

**Issue by DanielSeehausen** [learn-co-curriculum/omniauth_lab#11]
Fbook now requiring https. While this lab and previous readme (omniauth_readme) were updated, it is more of a patch (using https with rails is cumbersome). This lab should be updated to along with the previous readme to more seamlessly work with fbooks https requirement or we should switch platform to someone not requiring ssl on redirect uris.

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
