### ISSUE TITLE
Register a new OAuth Application Issue with Github

### ISSUE THREAD

**Issue by barrettanderson** [learn-co-curriculum/omniauth_lab#27]
Hello!

On the Authorization Callback URL screenshot for github, it says to have the callback website as http://localhost:3000/app/github/callback.  It should be http://localhost:3000/auth/github/callback.  Otherwise it gives a route error message, and is looking for auth/github/callback.

**Comment by chienleow** [comment]
@barrettanderson thank you, this is very helpful! Learn.co team, please make appropriate changes to the lesson, thank you!

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
