### ISSUE TITLE
Guidance walkthru difference // Omniauth Lab

### ISSUE THREAD

**Issue by jchasse** [learn-co-curriculum/omniauth_lab#28]
Hello!

Noticed that in the lab that one screenshot in instructions has:

get '/**auth**/github/callback', to: 'sessions#create'

while the screenshot from github has:

/**app**/github/callback'

Confusing for me as a newbie! Hope this helps.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
