### ISSUE TITLE
Error: oauth 2 token needs to be sent in header 

### ISSUE THREAD

**Issue by IgoVeyner** [learn-co-curriculum/omniauth_lab#29]
Unable to finish the GitHub OAuth section as I kept running into an error telling me to include the oauth 2 token in the header. 

Was able to fix this by deleting the Gemfile.lock file and running bundle install for a fresh Gemfile.lock .

New versions of 
- activesupport
- actionview
- actionpack
- actioncable
- actionjob
- actionmodel
- activerecord
- activestorage
- io-like
- bootsnap
- railties
- omniauth-github
- rails
- rspec-rails 

My money is on the version of omniauth-github is outdated and needs to be updated in the Gemlock? (from 1.3.0 to 1.4.0)

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
