### ISSUE TITLE
Readme discrepancy

### ISSUE THREAD

**Issue by jsgoldb** [learn-co-curriculum/omniauth_lab#3]
In the readme:

There is already a view that outputs all the authenticaton data, as well as showing you the user's photo if one is provided.

I don't believe this was finished in the lab.

**Comment by AnnJohn** [comment]
thanks for raising this @jsgoldb. We'll look into ti soon.

**Comment by pletcher** [comment]
https://github.com/learn-co-curriculum/omniauth_lab/commit/a73d0c5653f33b1045e6ee583c2f448d6fc5809d
