### ISSUE TITLE
OAutho2::Error 

### ISSUE THREAD

**Issue by miloscomplex** [learn-co-curriculum/omniauth_lab#30]
I was unable to login with omniauth-github until I ran `bundle update` to bring it up-to-date `omniauth-github 1.4.0 (was 1.3.0)` I was receiving an error after approving logging in with git-hub `Must specify access token via Authorization header` instead of displaying `home.html.erb` 

![image](https://user-images.githubusercontent.com/66390054/99932747-9e1e8080-2d1e-11eb-9d18-afcb518706b5.png)

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
