### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by milos381** [learn-co-curriculum/omniauth_lab#31]
`: {"message":"Must specify access token via Authorization header","documentation_url":"https://docs.github.com/v3/#oauth2-token-sent-in-a-header"}`

Two TCs weren't able to resolve this issue, I've spent 3 hours on google trying to figure it out, but bottom line is, the lab is not working. :) I AM passing all the tests, but it's not working properly in the browser.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
